sonar.projectKey=minolingo-frontend
sonar.projectName=Minolingo Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,src/**/*.spec.ts,src/**/*.test.ts,src/**/*.config.ts,src/main.ts,src/main.server.ts,src/server.ts,src/**/*.html,src/**/*.css,public/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
