apiVersion: apps/v1
kind: Deployment
metadata:
  name: minolingo-frontend
  labels:
    app: minolingo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minolingo-frontend
  template:
    metadata:
      labels:
        app: minolingo-frontend
    spec:
      containers:
        - name: minolingo-frontend
          image: mahmoud3331/minolingo-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:1.3.0
          args:
            - --nginx.scrape-uri=http://localhost/nginx_status
          ports:
            - name: metrics
              containerPort: 9113
